default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fair_exercise
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: fair_exercise

test:
  <<: *default
  database: fair_exercise_test

production:
  adapter: postgresql
  encoding: unicode
  database: fair_exercise_production
  username: fair_exercise
  password: <%= ENV['FAIR_EXERCISE_DATABASE_PASSWORD'] %>
